name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.30'

      - name: Configure CMake
        run: cmake -B build -G "MinGW Makefiles"

      - name: Build the project
        run: cmake --build build --config Release

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: arrayManipulation
          path: build/*.exe  # Adjust the path to match your executable
