name: Build CMake Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies for Ubuntu
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y cmake g++ gcc make

      # Install and configure MSYS2 for Windows
      - name: Set up MSYS2 and install dependencies (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-g++
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make

      - name: Configure CMake (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          cmake -B build -G "Unix Makefiles"

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          cmake -B build -G "MinGW Makefiles"

      - name: Build (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          cmake --build build -- -j$(nproc)

      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          cmake --build build -- -j$(nproc)
